global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Gateway Service
  - job_name: 'gateway-service'
    static_configs:
      - targets: ['gateway-service:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Team Service
  - job_name: 'team-service'
    static_configs:
      - targets: ['team-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Sanction Service
  - job_name: 'sanction-service'
    static_configs:
      - targets: ['sanction-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
